name: Checks

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - edited

jobs:
  checks:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: wip/action@master
    steps:
      - uses: liri-infra/xdg-validator-action@master
