name: Checks

on:
  push:
    branches:
      - master
      - develop
    tags:
      - v*
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - edited

jobs:
  checks:
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: wip/action@master
        if: github.event_name == 'pull_request'
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: liri-infra/xdg-validator-action@master
        with:
          strict: false
